### ISSUE TITLE
Unable to destroy attachments in embedded documents

### ISSUE THREAD

**Issue by mhayes** [mrrooijen/mongoid-paperclip#13]
First off, thanks to everyone who helped make this gem possible.  It's been great to work with, but I just started to notice some issues when working with embedded documents that happen to have paperclip attachments.  When I delete the parent object (in this case Slide) then the images still exist on the local filesystem.  In order to destroy the attachments is there another step I must perform in this case?

Here's the code that I'm currently using:

``` ruby
class Riff
  include Mongoid::Document
  include Mongoid::Paperclip
  embedded_in :slide
  has_mongoid_attached_file :slide_image,
    :styles => {:original => "800>", :thumb => "180x120#"},
    :path => 'public/system/riffs/:id/:style.:extension',
    :url => '/system/riffs/:id/:style.:extension'
end
```

Please let me know if there's any other information I should provide, thanks!

**Comment by FarihulR** [comment]
hei @meskyanichi i have a problem like that, i can't delete child object, 
How can delete Riff object ?
