### ISSUE TITLE
I looks like there is a new amazon gem

### ISSUE THREAD

**Issue by tbbooher** [mrrooijen/mongoid-paperclip#23]
paperclip now requires, aws-sdk -- if you use aws-s3, you get:

    LoadError in BlogsController#update

    no such file to load -- aws-sdk (You may need to install the aws-sdk gem)
    Rails.root: /app

    Application Trace | Framework Trace | Full Trace
    app/models/blog.rb:40:in `page_tokens='
    app/controllers/blogs_controller.rb:56:in `block in update'
    app/controllers/blogs_controller.rb:55:in `update'
    This error occurred while loading the following files:
    aws-sdk

**Comment by tilsammans** [comment]
This has since been released.
