### ISSUE TITLE
undefined method `logger' for Mongoid::Config:Module

### ISSUE THREAD

**Issue by taemon1337** [mrrooijen/mongoid-paperclip#32]
Using
-rails 3.2.6
-mongoid ~> 3.0.3 (currently 3.0.3)
-mongoid-paperclip

I am getting 'undefined method `logger' for Mongoid::Config:Module'

it looks like 'mongoid_paperclip.rb:15' is trying to do this
if Mongoid::Config.logger.present?
Mongoid::Config.logger
else
Rails.logger
end

but as of this fix, it is Mongoid.logger ( https://github.com/mongoid/mongoid/issues/2221 ).

First 3 of FULL TRACE:
mongoid-paperclip (0.0.7) lib/mongoid_paperclip.rb:15:in logger'
paperclip (3.1.4) lib/paperclip/logger.rb:6:inlog'
paperclip (3.1.4) lib/paperclip/instance_methods.rb:29:in `prepare_for_destroy'

Thanks,

**Comment by tilsammans** [comment]
`mongoid-paperclip` does nothing to the logger anymore, you can safely use version 0.0.10 or higher.
