### ISSUE TITLE
Photo is not recognized by the 'identify' command.

### ISSUE THREAD

**Issue by asisin1** [mrrooijen/mongoid-paperclip#33]
I'm migrating from Active Record to Mongoid, and this paperclip stuff used to work fine.

I've defined this in my mongoid document:

  has_mongoid_attached_file :photo,
  :styles => {
    :thumb  => "60x60",
    :small => "100x100",
    :medium => "300x200",
    :large => "600x400"
  },
  :storage => :s3,
  :s3_credentials => "#{Rails.root}/config/s3.yml",
  :path => "#{Rails.env}/merc_:attachment/:id/:style.:extension",
  :url => ":s3_alias_url",
  :bucket => '%^&*&^'

I have the rmagick gem installed and also have the command_path pointing to where the various imagemagick commands are.

I'm using Unicorn as my webserver, and I have verified that identiy and convert are available by putting this in my view:

<%= `which convert` %>
<%= `echo $PATH` %>

But alas, when I try to upload the image I get :

Photo /tmp/qdoba20121005-27609-1m3kq9c.jpg is not recognized by the 'identify' command.
Photo /tmp/qdoba20121005-27609-1m3kq9c.jpg is not recognized by the 'identify' command.
Photo /tmp/qdoba20121005-27609-1m3kq9c.jpg is not recognized by the 'identify' command.
Photo /tmp/qdoba20121005-27609-1m3kq9c.jpg is not recognized by the 'identify' command.

seemingly one for every one of the styles I have defined. 

Help!

**Comment by tilsammans** [comment]
This does not seem to be related to `mongoid-paperclip` but to `paperclip` itself.

If you feel that this issue _is_ caused by `mongoid-paperclip` then please clarify and I can investigate.

**Comment by nadeemyasin61** [comment]
@tilsammans yes, it was figured out not to be related to `mongoid-paperclip`.
