### ISSUE TITLE
rake paperclip:refresh failed

### ISSUE THREAD

**Issue by patricklehmann** [mrrooijen/mongoid-paperclip#41]
Hi there,

I want to refresh my thumbs so i do rake paperclip:refresh CLASS=Store::Product
and this is what i get:

rake aborted!
The operation: #<Moped::Protocol::Query
  @length=133
  @request_id=3
  @response_to=0
  @op_code=2004
  @flags=[:slave_ok]
  @full_collection_name="creative_tool_ple_bli_ch_development.store.products"
  @skip=0
  @limit=0
  @selector={"$where"=>"preview_image_file_name IS NOT NULL"}
  @fields=nil>
failed with error 16722: "JavaScript execution failed: SyntaxError: Unexpected identifier"

See https://github.com/mongodb/mongo/blob/master/docs/errors.md
for details about this error./usr/local/rvm/gems/ruby-1.9.3-p429/gems/moped-1.5.0/lib/moped/node.rb:382:in `block in query'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/moped-1.5.0/lib/moped/node.rb:587:in `[]'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/moped-1.5.0/lib/moped/node.rb:587:in `block (3 levels) in flush'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/moped-1.5.0/lib/moped/node.rb:586:in `map'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/moped-1.5.0/lib/moped/node.rb:586:in `block (2 levels) in flush'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/moped-1.5.0/lib/moped/node.rb:150:in `ensure_connected'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/moped-1.5.0/lib/moped/node.rb:582:in `block in flush'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/moped-1.5.0/lib/moped/node.rb:597:in `logging'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/moped-1.5.0/lib/moped/node.rb:581:in `flush'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/moped-1.5.0/lib/moped/node.rb:570:in `process'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/moped-1.5.0/lib/moped/node.rb:370:in `query'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/moped-1.5.0/lib/moped/cursor.rb:138:in `block in load_docs'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/moped-1.5.0/lib/moped/session/context.rb:105:in `block in with_node'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/moped-1.5.0/lib/moped/cluster.rb:251:in `with_secondary'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/moped-1.5.0/lib/moped/session/context.rb:104:in `with_node'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/moped-1.5.0/lib/moped/cursor.rb:137:in `load_docs'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/moped-1.5.0/lib/moped/cursor.rb:25:in `each'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/moped-1.5.0/lib/moped/query.rb:76:in `each'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/moped-1.5.0/lib/moped/query.rb:76:in `each'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/mongoid-3.1.4/lib/mongoid/contextual/mongo.rb:122:in `block in each'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/mongoid-3.1.4/lib/mongoid/contextual/mongo.rb:619:in `selecting'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/mongoid-3.1.4/lib/mongoid/contextual/mongo.rb:121:in `each'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/mongoid-3.1.4/lib/mongoid/contextual.rb:19:in `each'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/mongoid-3.1.4/lib/mongoid/criteria.rb:510:in `entries'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/mongoid-3.1.4/lib/mongoid/criteria.rb:510:in `method_missing'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/paperclip-3.5.1/lib/paperclip/helpers.rb:37:in `each_instance_with_attachment'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/paperclip-3.5.1/lib/tasks/paperclip.rake:66:in `block (4 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/paperclip-3.5.1/lib/tasks/paperclip.rake:65:in `each'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/paperclip-3.5.1/lib/tasks/paperclip.rake:65:in `block (3 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-1.9.3-p429/bin/ruby_noexec_wrapper:14:in `eval'
/usr/local/rvm/gems/ruby-1.9.3-p429/bin/ruby_noexec_wrapper:14:in `<main>'
Tasks: TOP => paperclip:refresh => paperclip:refresh:metadata
(See full trace by running task with --trace)

Can someone help?

Kind regards, patrick

**Comment by tilsammans** [comment]
Was already fixed, added a test in ada3c3f0d4082bbeb96317835f87c785366791dc.
