### ISSUE TITLE
uninitialized constant Mongoid::Paperclip

### ISSUE THREAD

**Issue by pwen** [mrrooijen/mongoid-paperclip#53]
Raising 'uninitialized constant Mongoid::Paperclip' in model:

class Photo
  include Mongoid::Document
  include Mongoid::Timestamps::Short
  include Mongoid::Paperclip

  has_mongoid_attached_file :attachment
  embedded_in :story, :inverse_of => :photos
end

Rails 4.0.4
Ruby 2.0.0
Relevant gem versions:
    mongoid (4.0.0.beta1)
    mongoid-paperclip (0.0.9)
      paperclip (>= 2.3.6)
    aws-sdk (1.3.9)
      httparty (~> 0.7)
      json (~> 1.4)
      nokogiri (>= 1.4.4)
      uuidtools (~> 2.1)
    mongoid-rspec (1.10.0)
      mongoid (>= 3.0.1)
      rake
      rspec (>= 2.14)

**Comment by tilsammans** [comment]
As mentioned, version 0.0.10 and lower should use `require: 'mongoid_paperclip'` in Gemfile.

This will be remedied in versions later than 0.0.10.
