### ISSUE TITLE
Refresh missing styles

### ISSUE THREAD

**Issue by daninfpj** [mrrooijen/mongoid-paperclip#57]
The paperclip gem includes a rake task (rake paperclip:refresh:missing_styles) to refresh missing styles after deploying.

However, it fails when using mongoid:
undefined method `find_each' for #<Mongoid::Criteria:0x00…>

There's some suggested fix here:
https://github.com/thoughtbot/paperclip/issues/1064

**Comment by tilsammans** [comment]
Was already fixed, added a test in ada3c3f0d4082bbeb96317835f87c785366791dc.
