### ISSUE TITLE
URL Friendly Filenames

### ISSUE THREAD

**Issue by bhellman1** [mrrooijen/mongoid-paperclip#58]
Has anyone gotten mongoid-paperclip to handle filenames with non-alphanumeric characters? 

For example, uploading a file with the filename `A1/2/3/.png` silently fails. Newer versions of paperclip have a `cleanup_filename` method which is not present in this version of mongoid-paperclip. I've also tried adding `before_post_process` which works for paperclip but does not with mongoid-paperclip.

Suggestions? Thanks

**Comment by tilsammans** [comment]
`mongoid-paperclip` can use any version of `paperclip`. You should have no trouble upgrading to the latest & greatest paperclip now. If you do, please open a new issue!
