### ISSUE TITLE
Do not works with rails 4.2 and mongoid 4

### ISSUE THREAD

**Issue by makshark** [mrrooijen/mongoid-paperclip#66]
How it cab be solve?

**Comment by sivagollapalli** [comment]
@makshark I think maybe this(https://github.com/mrrooijen/mongoid-paperclip/pull/62) is the issue you might have faced. If not, could you paste error gist?

**Comment by tilsammans** [comment]
I cannot reproduce your error.

We are currently testing with Rails 4.2.6 and mongoid 5.1.3.

Please provide a stack trace and version information for the problem you're having and I can reopen this issue. I don't think we will support Mongoid 4 any more though.
