### ISSUE TITLE
URI::InvalidURIError: URI must be ascii only "http://xiaoniu-ads.oss-cn-hangzhou.aliyuncs.com/a/pic_paths/57bb/ad83/d44f/2108/cbae/ed45/\u{6cf8}\u{5dde}\u{8d21}.jpg"

### ISSUE THREAD

**Issue by lehug** [mrrooijen/mongoid-paperclip#72]
environment : rails4.2.5,mongoid-paperclip:0.0.10.
when I destroy a record,it rails with "URI::InvalidURIError: URI must be ascii only "http://xiaoniu-ads.oss-cn-hangzhou.aliyuncs.com/a/pic_paths/57bb/ad83/d44f/2108/cbae/ed45/\u{6cf8}\u{5dde}\u{8d21}.jpg"",exactlly my file name contails Chinese,when change the url with Chinese,than it can get.

what can I do to destroy it? or what can i do to let filename from Chinese(UTF_8) to ASCII ?

**Comment by tilsammans** [comment]
I am pretty sure this is a problem with `paperclip`, not with `mongoid-paperclip`.

Do you have a stack trace?

**Comment by lehug** [comment]
happend in:
URI::InvalidURIError: URI must be ascii only "http://xiaoniu-ads.oss-cn-hangzhou.aliyuncs.com/a/pic_paths/57bb/ad83/d44f/2108/cbae/ed45/\u{6cf8}\u{5dde}\u{8d21}.jpg"
from /Users/jyd-9062/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/uri/rfc3986_parser.rb:21:in `split'

**Comment by tilsammans** [comment]
I'm afraid it's not a problem in this gem. We do not have URI parse code in it.

It's a problem in [paperclip gem](https://github.com/thoughtbot/paperclip) and you have to ask your question there, or on [StackOverflow](http://stackoverflow.com).
