### ISSUE TITLE
Change dependency to maintained gem kt-paperclip

### ISSUE THREAD

**Issue by megatux** [mrrooijen/mongoid-paperclip#79]
Main Paperclip gem is [deprecated now](https://rubygems.org/gems/kt-paperclip) and they recommend to use [this fork](https://rubygems.org/gems/kt-paperclip). I think we should move this library dependency on that gem.

**Comment by megatux** [comment]
Just created a fork [here](https://github.com/megatux/mongoid-paperclip) with this change.

**Comment by jarthod** [comment]
Agreed, I can't upgrade to ruby 3.0.3 because of the dependency on paperclip, I was able to do so on another project by switching to `kt-paperclip` but with `mongoid-paperclip` we would need

**Comment by tilsammans** [comment]
Yes, looks like I'll be able to do that in the next few days.

Adrien Rey-Jarthon ***@***.***> schreef op 2 januari 2022 20:39:45 CET:
>Agreed, I can't upgrade to ruby 3.0.3 because of the dependency on paperclip, I was able to do so on another project by switching to `kt-paperclip` but with `mongoid-paperclip` we would need to change the gemspec.
>
>Thanks for the fork @megatux, it looks like you replaced the wrong line though (mongoid instead of paperclip):
>![image](https://user-images.githubusercontent.com/201687/147887327-022a1652-5002-4acb-bb0d-46cba2cdbc35.png)
> 
***@***.*** @tilsammans would you be interested in a PR for this change?

**Comment by jarthod** [comment]
Ok great. There's already many forks doing this change, I ended up using one of them: https://github.com/aplaut-tech/mongoid-paperclip. I can't open a PR with someone else's fork but you can merge this branch for example.
If you prefer me to create another fork so I can open a PR directly let me know!

**Comment by megatux** [comment]
I updated my fork to fix the gem change and updated deps.

**Comment by jarthod** [comment]
@megatux great thanks! Could you please open a PR with your branch? And maybe update the readme a bit too? in order to reduce the work of @tilsammans.

**Comment by megatux** [comment]
@jarthod created the PR and updated the Readme a bit. Hope this helps. Regards.

**Comment by jarthod** [comment]
Thanks @megatux ! for the record it's #81

**Comment by tilsammans** [comment]
I'll get on it tomorrow.
Going to be a major version bump, probably.

Adrien Rey-Jarthon ***@***.***> schreef op 4 januari 2022 17:21:08 CET:
