### ISSUE TITLE
Including two image files in model causes error

### ISSUE THREAD

**Issue by victorbstan** [mrrooijen/mongoid-paperclip#8]
I have a model with two calls to "has_mongoid_attached_file" 

Whichever appears first (in the model) causes an error in the view:

ActionView::Template::Error (can't convert nil into Hash):
    7:     = f.input :background
    8:     = f.input :logo
  app/views/pages/_form.html.haml:8:in `block in _app_views_pages__form_html_haml___272641787_101432820'
  app/views/pages/_form.html.haml:1:in `_app_views_pages__form_html_haml___272641787_101432820'
  app/views/pages/new.html.haml:3:in `_app_views_pages_new_html_haml___754983345_101515850'
  app/controllers/pages_controller.rb:48:in `new'

**Comment by tilsammans** [comment]
This works and I've added a test for it in 3769914.
